// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gleo/subscribers/common/postgres"
	"github.com/gleo/subscribers/internal/adapter/deadletter"
	dead_letter_replay "github.com/gleo/subscribers/internal/application/job/dead-letter-replay"
	"github.com/gleo/subscribers/internal/domain"
	"github.com/gleo/subscribers/pkg/workflow"
)

// Injectors from wire.go:

func WireReplayWorkflow(cfg dead_letter_replay.DeadLetterReplayConfig) (*workflow.Workflow[domain.DeadLetter], error) {
	postgresConfig := dead_letter_replay.WirePostgresConfig(cfg)
	db, err := postgres.NewGormDB(postgresConfig)
	if err != nil {
		return nil, err
	}
	deadLetterRepository, err := deadletter.NewDeadLetterRepository(db)
	if err != nil {
		return nil, err
	}
	replayConfig := dead_letter_replay.WireReplayConfig(cfg)
	deadLetterEventSource := dead_letter_replay.NewDeadLetterSource(replayConfig, deadLetterRepository)
	eventStreamingConfig := dead_letter_replay.WireEventStreamingConfig(cfg)
	workflowSuppliers := dead_letter_replay.NewWorkflowSuppliers()
	deadLetterDispatcher := dead_letter_replay.NewDeadLetterDispatcher(deadLetterRepository, workflowSuppliers, eventStreamingConfig)
	replayWorkflow, err := dead_letter_replay.NewReplayWorkflow(deadLetterEventSource, deadLetterDispatcher)
	if err != nil {
		return nil, err
	}
	return replayWorkflow, nil
}
