// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/gleo/subscribers/common/kafka"
	"github.com/gleo/subscribers/common/postgres"
	"github.com/gleo/subscribers/internal/adapter/deadletter"
	"github.com/gleo/subscribers/internal/application/event-streaming"
	"github.com/gleo/subscribers/internal/application/event-streaming/common"
	"github.com/gleo/subscribers/internal/application/event-streaming/config"
	"github.com/gleo/subscribers/internal/application/event-streaming/util"
	"github.com/gleo/subscribers/pkg/partner"
	"github.com/gleo/subscribers/pkg/telemetry"
	"github.com/gleo/subscribers/pkg/workflow"
)

// Injectors from wire.go:

func WireNotifyWorkflow(cfg config.EventStreamingConfig) (*workflow.Workflow[workflow.KafkaMessage], error) {
	readerConfig := event_streaming.WireKafkaReaderConfig(cfg)
	reader := kafka.NewReader(readerConfig)
	eventSource := workflow.NewSegmentIOSource(reader)
	postgresConfig := event_streaming.WirePostgresConfig(cfg)
	db, err := postgres.NewGormDB(postgresConfig)
	if err != nil {
		return nil, err
	}
	deadLetterRepository, err := deadletter.NewDeadLetterRepository(db)
	if err != nil {
		return nil, err
	}
	deadLetterProcessor := util.NewDeadLetterProcessor(deadLetterRepository)
	retryOption := event_streaming.WireRetryOptionConfig(cfg)
	retry := workflow.NewRetry(retryOption)
	notifyEventParser := util.NewEventParser()
	maxWaitDuration := event_streaming.WireMaxWaitConfig(cfg)
	maxWait := workflow.NewMaxWait(maxWaitDuration)
	partnerConfig := event_streaming.WirePartnerConfig(cfg)
	client := partner.NewPartnerClient(partnerConfig)
	notifier := event_streaming.NewNotifier(client)
	workflowWorkflow, err := event_streaming.NewNotifyWorkflow(eventSource, deadLetterProcessor, retry, notifyEventParser, maxWait, notifier)
	if err != nil {
		return nil, err
	}
	return workflowWorkflow, nil
}

// wire.go:

func WireExporter(cfg config.EventStreamingConfig) *telemetry.Exporter {
	exporterConfig := event_streaming.WireMetricConfig(cfg)
	return telemetry.NewExporter(exporterConfig)
}

func GetWorkflow(name string, cfg config.EventStreamingConfig) (*workflow.Workflow[workflow.KafkaMessage], error) {
	switch name {
	case common.NotifyWorkflowName:
		return WireNotifyWorkflow(cfg)
	default:
		return nil, fmt.Errorf("wire: unknown workflow %q", name)
	}
}
